### PR TITLE
Adding French BEPO layout for XP15

### PR DESCRIPTION
**Pull request by n-tux-tmp**
Hi,

I'm adding layouts for the French official [BÉPO](https://bepo.fr/) keyboard:
image

In this PR you'll find:

- BÉPO (ISO) with Rajdhani font ;
- BÉPO (ISO) with Rajdhani font and a custom logo for the TUX key ;
- BÉPO (ISO) with Arial font ;
- BÉPO (ISO) with Arial font and a custom logo for the TUX key.

I have a slight preference for the Arial font in this case, because Rajdhani does not support all characters from the BÉPO keyboard.

The BÉPO + Arial + custom logo is the one I'd like to use for my personal laptop, if you don't mind.

I used [klf2tux](https://git.42l.fr/neil/klf2tux) to convert XKB keymaps to SVG layouts.

This PR does not include symbolic links for identical layouts (e.g. Aura 15, BC15...).

### CODE REVIEW

**Comment by vser1** [comment]
BÉPO is standardized by the French AFNOR (the french DIN) under the norm NF ZF1-300. @n-tux-tmp is your layout compliant?

**Comment by n-tux-tmp** [comment]
> BÉPO is standardized by the French AFNOR (the french DIN) under the norm NF ZF1-300. @n-tux-tmp is your layout compliant?

The AFNOR standard layout is the simplified version of the layout I've submitted. The simplified version displays less keys.

If you check the official website: http://bepo.fr/wiki/Accueil

The simplified version is displayed on their homepage, hover your mouse on it and you'll see the full version. The layout I've submitted matches the full version, minus all the duplicate keys (mainly lowercase letters).

So, my layout displays more keys than the simplified version (which is a personal design choice), though I haven't added or moved any key that isn't part of the official specification.

**Comment by n-tux-tmp** [comment]
@vinzv Hi! would you mind reviewing this PR and tell me about possible adjustements I need to apply?

You'll probably have to choose between Rajdhani and Arial fonts.

Thank you!

**Comment by vinzv** [comment]
Thanks a lot for your contribution! :+1:

**Pull request merged**
