### PR TITLE
Added Neo Layout

### PR DESCRIPTION
**Pull request by OddDev**
Neo is an ergonomic layout mainly for the German language
Commonly keyboards feature only the first layer
More information: https://neo-layout.org/

### CODE REVIEW

**Comment by uaparit** [comment]
Hi OddDev,
did you already use this Layout at your Tuxedo order? Are the positions of the letters on the keys are fine?
greets uaparit

**Comment by OddDev** [comment]
> Hi OddDev, did you already use this Layout at your Tuxedo order? Are the positions of the letters on the keys are fine? greets uaparit

Hey :) 
I didn't order my computer yet. However, if _you_ do so with this layout, they will tell you if anything is wrong with it. So you are safe to go.

**Comment by uaparit** [comment]
Thx for the hint that they will check/test the Layout. I must have overlooked that.
Nevertheless i made another layout because i like to have the layers 2-4.

**Comment by vinzv** [comment]
Thanks for your contribution! :+1:

**Pull request merged**
